---
title: "Further Exploration on Homework0"
author: "zl2974"
date: "2020/9/11"
output:   html_document
always_allow_html: true

    
---
```{r setup, echo=FALSE,message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(car)
library(gridExtra)
library(leaflet)
data('nyc_airbnb')
```

# Data Exploring on Question 1

First we look at the data
```{r data_cleaning, collapse=TRUE}
nyc_airbnb_clean <- nyc_airbnb %>%
  filter(
    !is.na(review_scores_location)
  ) %>%
  mutate(
    neighbourhood_group=as.factor(neighbourhood_group),
    room_type=as.factor(room_type),
    sqrt_review_scores_location=sqrt(review_scores_location),
    log_price=log(price),
    log_number_of_reviews=log(number_of_reviews)
    )
skimr::skim(nyc_airbnb_clean)

```

In order to look at the relationship with review's scores. But first we should notice there's extreme left skewness in scores, even though adjusted with square roof.

```{r analysis on review}
pairs(~sqrt_review_scores_location+log_price+log_number_of_reviews,nyc_airbnb_clean)

nyc_airbnb_clean%>%
  group_by(neighbourhood_group)%>%
  summarise(mean_scores=mean(sqrt_review_scores_location))

plt=c()
for (i in c(1:2)){
  var=c('neighbourhood_group','room_type')[[i]]
  plt[[i]]<-ggplot(nyc_airbnb_clean,
  aes_string(y='sqrt_review_scores_location',x = var, fill=var
      ))+
  geom_boxplot()
}
grid.arrange(plt[[1]],plt[[2]],ncol=1)

```

# Question 2 on price
```{r price_relation,message=FALSE,collapse=TRUE}
plt=c()
for (i in c(1:2)){
  var=c('neighbourhood_group','room_type')[[i]]
  plt[[i]]<-ggplot(nyc_airbnb_clean,
  aes_string(y='log_price',x=var,fill=var
      ))+
  geom_violin()
}
grid.arrange(plt[[1]],plt[[2]],ncol=1)
```



# Question 3

Now we check where the landlord located in:

```{r map_plot}
map_data <- nyc_airbnb_clean%>%
  group_by(neighbourhood)%>%
  summarise(
    rental_locate = n(),
    lat = mean(lat),
    long = mean(long)
  )
m <- leaflet::leaflet(map_data)%>%
  addProviderTiles(providers$CartoDB.Positron) %>% #addTiles()%>%
  addCircles(
    lat=~long,lng = ~lat,popup=~as.character(rental_locate),label=~neighbourhood,
    radius = ~sqrt(rental_locate)*40,weight=1
  )
  #addMarkers(~long,~lat,popup = ~host_name,label = ~review_scores_location)
m
```

